M48
; DRILL file {KiCad 7.0.7+dfsg-1} date Mon 25 Mar 2024 16:35:43 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-25T16:35:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7+dfsg-1
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0433
%
G90
G05
T1
X6.2467Y-2.8467
X6.2467Y-2.886
X6.286Y-2.8467
X6.286Y-2.886
T2
X6.25Y-2.5
X6.25Y-2.5787
X6.25Y-2.6575
T3
X5.4Y-2.2
X5.5Y-2.2
X5.6Y-2.2
X5.7Y-2.2
X5.8Y-2.2
T4
X5.75Y-3.961
X5.75Y-4.15
X5.75Y-4.339
T0
M30
